pytorch 의 공식 tutorial page 인 https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html 부분을 그대로 옮겼습니다.
간단한 개념들이라서 따로 주석으로 설명하진 않고 수업시간 중에 설명드리도록 하겠습니다 :)

In [41]:
import torch
import torchvision

In [42]:
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [43]:
x = torch.rand(5,3)
print(x)

tensor([[0.3528, 0.5483, 0.7203],
        [0.7564, 0.2118, 0.6097],
        [0.2870, 0.3693, 0.2792],
        [0.5108, 0.6930, 0.8368],
        [0.9765, 0.3309, 0.1441]])


In [44]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [45]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [46]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float32)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4240, -1.4086,  0.7656],
        [ 1.4587, -0.0169, -2.0805],
        [-0.0763, -0.4713,  0.0063],
        [ 1.0371,  0.0592, -1.1366],
        [-0.7892,  0.1222,  1.1642]])


In [47]:
print(x.size())

torch.Size([5, 3])


In [48]:
y = torch.rand(5,3, dtype=torch.double)
print(x+y)

tensor([[ 1.3376, -1.2095,  1.1010],
        [ 2.3294,  0.3747, -1.0956],
        [ 0.4286,  0.0660,  0.7174],
        [ 1.9269,  0.2480, -0.3899],
        [ 0.0661,  0.5949,  1.9980]], dtype=torch.float64)


In [49]:
print(torch.add(x,y))

tensor([[ 1.3376, -1.2095,  1.1010],
        [ 2.3294,  0.3747, -1.0956],
        [ 0.4286,  0.0660,  0.7174],
        [ 1.9269,  0.2480, -0.3899],
        [ 0.0661,  0.5949,  1.9980]], dtype=torch.float64)


In [50]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3376, -1.2095,  1.1010],
        [ 2.3294,  0.3747, -1.0956],
        [ 0.4286,  0.0660,  0.7174],
        [ 1.9269,  0.2480, -0.3899],
        [ 0.0661,  0.5949,  1.9980]])


In [51]:
y.add_(x)
print(y)

tensor([[ 1.3376, -1.2095,  1.1010],
        [ 2.3294,  0.3747, -1.0956],
        [ 0.4286,  0.0660,  0.7174],
        [ 1.9269,  0.2480, -0.3899],
        [ 0.0661,  0.5949,  1.9980]], dtype=torch.float64)


In [52]:
print(x)
print(x[:, 1])

tensor([[ 0.4240, -1.4086,  0.7656],
        [ 1.4587, -0.0169, -2.0805],
        [-0.0763, -0.4713,  0.0063],
        [ 1.0371,  0.0592, -1.1366],
        [-0.7892,  0.1222,  1.1642]])
tensor([-1.4086, -0.0169, -0.4713,  0.0592,  0.1222])


In [53]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(2,-1)
print( x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [54]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0333])
0.03327479213476181


In [55]:
a = torch.ones(5)
print(a)
type(a)

tensor([1., 1., 1., 1., 1.])


torch.Tensor

In [56]:
b = a.numpy()
print(b)
type(b)

[1. 1. 1. 1. 1.]


numpy.ndarray

In [57]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [58]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [59]:

if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

## autograd


In [60]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [21]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [22]:
print(y.grad_fn)

In [23]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [24]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [25]:

out.backward()


In [26]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [27]:

x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
    
print(y)

tensor([-724.6842,   31.6857, 1750.1122], grad_fn=<MulBackward0>)


In [28]:
v = torch.randn(3)
y.backward(v)

print(x.grad)

tensor([ -29.5425, 2674.6406, 1822.8730])


In [29]:

print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [30]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


## simple neural network

In [31]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16*6*6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *=s 
        return num_features
    
net = Net()
print(net)
        
        
        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [32]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [33]:

input = torch.randn(1,1,32,32)
out = net(input)
print(out)

tensor([[ 0.0535, -0.1187,  0.0111,  0.0978, -0.0352,  0.1082,  0.1450,  0.0716,
         -0.0085, -0.0787]], grad_fn=<AddmmBackward>)


In [34]:
net.zero_grad()
out.backward(torch.randn(1,10))

In [35]:
output = net(input)
target = torch.randn(10)
target = target.view(1,-1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)


tensor(1.4649, grad_fn=<MseLossBackward>)


In [36]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

In [37]:
net.zero_grad()

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad before backward
tensor([-0.0197, -0.0148, -0.0026,  0.0146,  0.0170,  0.0487])


In [38]:
learning_rate = 0.01
for f in net.parameters():
    f = f - f.grad.data * learning_rate
    #f.data.sub_(f.grad.data * learning_rate)

In [39]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()