In [1]:
import torch
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:

# 2x3 ( 2 rows, 3 columns )
my_tensor = torch.tensor(
    [ [1,2,3], [4,5,6]], dtype=torch.float32, device=device, requires_grad=True
)

In [6]:
print(my_tensor.dtype, my_tensor.device, my_tensor.shape, my_tensor.requires_grad)

torch.float32 cuda:0 torch.Size([2, 3]) True


In [25]:
# 다른 형태의 helper 를 이용한 tensor 정의 방법들

x = torch.empty(size=(3,3))
x = torch.zeros((3,3))   #  zeros(3,3) 이 아님을 유의
x = torch.rand((3,3))   # 3x3 uniform distribution [0,1]
x = torch.eye(5,5)
x = torch.arange( start=0, end=5, step=0.1, dtype=torch.float64)
x = torch.linspace(start=0.1, end=1, steps=10)
x = torch.empty( size=(1,5)).normal_( mean=0, std=1 ) 
x = torch.empty( size=(1,5)).uniform_( 0, 1)
x = torch.diag(torch.ones(3))



In [35]:
t = torch.arange(4)
print(t.bool())
print(t.short()) #  dtype=torch.int16 으로 변환
print(t.long())
print(t.half())  #  원래의 float32 에서 float16 으로 변환
print(t.float()) #   float32 가 default value
print(t.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [39]:
np_array = np.zeros((5,5))
t = torch.from_numpy(np_array)
np_array_again = t.numpy()


In [48]:

x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

z1 = torch.empty(3)
torch.add(x, y, out=z1)
z2 = torch.add(x,y)
z = x + y

z = x - y   

z = torch.true_divide(x, y)  # element-wise division 

t = torch.zeros(3)
t.add_(x)   #   끝에 _ 를 붙히면 tensor 안에 있는 내용을 mutate 시킨다.
print(t)
t = t + x
print(t)

z = x.pow(2)
z = x ** 2  # 똑같은 표현


z = x > 0     # [True, True, True]
z = x < 0     # [False, False, False]

# matrix multiplication 

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm( x1, x2) # 
x3 = x1.mm(x2)


# matrix exponentiation 

matrix_exp = torch.rand(5,5)
print(matrix_exp)
print(matrix_exp.matrix_power(3))

z = x * y    #    element-wise multiplication

z = torch.dot(x,y)   # dot product 


tensor([1., 2., 3.])
tensor([2., 4., 6.])
tensor([[0.1519, 0.3852, 0.4337, 0.2215, 0.9684],
        [0.5537, 0.0550, 0.0554, 0.8018, 0.8557],
        [0.8642, 0.8678, 0.2414, 0.0062, 0.4056],
        [0.2332, 0.5582, 0.7583, 0.7612, 0.2218],
        [0.5649, 0.2614, 0.3992, 0.4100, 0.2449]])
tensor([[2.0328, 1.9135, 1.8165, 2.0186, 2.6190],
        [2.5110, 2.3084, 1.9562, 2.2081, 2.5899],
        [2.3583, 2.0617, 2.1643, 2.3334, 2.5497],
        [2.7150, 2.4004, 2.2546, 2.7059, 3.3015],
        [2.0529, 1.7248, 1.5848, 1.8974, 2.2712]])


In [52]:
# batch matrix multiplication

batch = 32
n = 10
m = 20
p = 30

t1 = torch.rand((batch, n, m))
t2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(t1, t2)   #     ( b x n x p)

print(t1.shape, t2.shape, out_bmm.shape)   # batch matrix product 

torch.Size([32, 10, 20]) torch.Size([32, 20, 30]) torch.Size([32, 10, 30])


In [58]:
# tensor broadcasting

x1 = torch.rand((5,5))
x2 = torch.ones((1,5))
print(x1.shape, x2.shape)

z = ( x1 - x2)
print(z)
z = ( x1 ** x2)
print(z)


torch.Size([5, 5]) torch.Size([1, 5])
tensor([[-0.2736, -0.2141, -0.9848, -0.7274, -0.7399],
        [-0.6250, -0.6181, -0.8786, -0.6728, -0.2390],
        [-0.8852, -0.0414, -0.3515, -0.5804, -0.0457],
        [-0.8581, -0.4022, -0.1177, -0.6736, -0.7106],
        [-0.1517, -0.7355, -0.8129, -0.7269, -0.7439]])
tensor([[0.7264, 0.7859, 0.0152, 0.2726, 0.2601],
        [0.3750, 0.3819, 0.1214, 0.3272, 0.7610],
        [0.1148, 0.9586, 0.6485, 0.4196, 0.9543],
        [0.1419, 0.5978, 0.8823, 0.3264, 0.2894],
        [0.8483, 0.2645, 0.1871, 0.2731, 0.2561]])


In [68]:

x = torch.tensor([[1,2,3], [4,5,6]])

sum_x = torch.sum( x, dim=0)   # dim=0 에서의 합 
print(sum_x)

tensor([5, 7, 9])


In [83]:
x = torch.tensor([1,2,3])
values, indicies = torch.max(x, dim=0)   #   x.max(dim=0)
values, indicies = torch.min(x, dim=0)   #   x.min(dim=0)
abs_x = torch.abs(x)


z = torch.argmax(x, dim=0)
z = torch.argmin(x, dim=0)
mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x, y)   # element-wise comparison 
sorted_y, indicies = torch.sort(y, dim=0, descending=False)

z = torch.clamp(x, min=0)   # ReLU 처럼 동작함

x = torch.tensor( [1,0,1,1,1], dtype=torch.bool)
z = torch.any(x)   # True
z = torch.all(x)   # False 

# dim=0 , dim=1 이 혼돈스러울 수 있음... 다음번에 multi-dimenstion dataset 을 다루면서 각각의 케이스에서의 behavior 를 익혀가는 것으로 ...

# Tensor Indexing


In [134]:
batch_size = 10
features =  25
x = torch.rand( (batch_size, features))

#print(x)

# numpy indexing 이랑 비슷해서 매우 혼돈스러움... 혼돈스러운 indexing 표현은 되도록이면 쓰지 않는 것을 권장.. 
print(x.shape)
print(x[0].shape)
print(x[:,0].shape) 
print(x[2, 0:10].shape)

x[0,0] = 100

torch.Size([10, 25])
torch.Size([25])
torch.Size([10])
torch.Size([10])


In [139]:
x = torch.arange(10)
indicies =  [ 0, 2, 8]
print(x[indicies])

x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows, cols])    # tricky 한 표현 ... numpy array indexing 이랑 같음... 그런데 이런 표현은 웬만하면 쓰지 않는 것을 권장 

tensor([0, 2, 8])
tensor([0.1997])


In [141]:

x = torch.arange(10)
print(x[ (x<2) | (x>8)])
print(x[ x.remainder(2) == 0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [144]:
print(x)
print( torch.where( x > 5, x*2, x))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  1,  2,  3,  4,  5, 12, 14, 16, 18])


In [147]:
x = torch.tensor([0,0,1,2,2,3,4]).unique()
print(x)
print(x.ndimension())
print(x.numel())

tensor([0, 1, 2, 3, 4])
1
5


# Tensor reshaping

In [88]:

x = torch.arange(9)
x = x.view(3,3)
x = x.reshape(3,3)    # reshape 은 memory 에 contiguous 하게 copy 하기 때문에 view 보다는 시간이 조금 더  걸림.. 그러나 그 다음부터 연산속도는 조금 더 빠름

y = x.t()
print(y.is_contiguous())     #  False 가 리턴됨 
y = x.t().reshape(-1)
print(y.is_contiguous())     #  True 가 리턴됨 

print(y.contiguous().view(9))



False
True
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [92]:
# dimenstion 에 따른 add operation 의 상이함에 대해서 이해해 보도록 하기

x1 = torch.rand(2,5)
x2 = torch.rand(2,5)
print(x1, x2)

print(torch.cat((x1,x2), dim=0).shape)    #   4x5      ( column-wide concatenation )
print(torch.cat((x1,x2), dim=1).shape)    #   2x10     ( row-wide concatenation )

# 이 부분 계속 혼돈스러운 것 알고 있음.... 일단 dim=0 은 column (세로)로  operation 하고, dim=1 은 row( 가로) 로 operation 하는 것으로 이해하고 넘어가자. 

tensor([[0.6084, 0.3850, 0.6542, 0.4312, 0.5375],
        [0.9946, 0.2912, 0.7616, 0.0570, 0.2484]]) tensor([[0.1833, 0.0126, 0.4294, 0.2522, 0.0937],
        [0.0299, 0.0784, 0.0827, 0.1017, 0.8215]])
torch.Size([4, 5])
torch.Size([2, 10])


In [94]:

z = x1.view(-1)     #  하나의 row-vector 로 다 unroll 해버림 
print(z)

tensor([0.6084, 0.3850, 0.6542, 0.4312, 0.5375, 0.9946, 0.2912, 0.7616, 0.0570,
        0.2484])


In [97]:

batch = 64
x = torch.rand((batch,2,5))   # 64 batch 의 2x5 training set 이라고 가정해보고..
z = x.view(batch,-1)  # batch 의 차원을 유지한채로 나머지를 다 unrolling 한다..  mninst dataset 의 28x28 을 fully-connected 에 넣어야 할때 바로 쓰게 된다.


## 또 한가지의 유요한 기능은 permute 에 대해서....  이를테면 batch 는 그대로 둔채로 dataset 의 column 과 row 를 바꾸어야 할 경우에  이렇게 쓸수 있음..

z = x.permute(0,2,1)  #  즉, dimension-1 에 있던 것을 dimension-2 로 바꾸라...


In [99]:
# TODO
z = torch.chunk(x, chunks=2, dim=1)
print(z[0].shape)
print(z[1].shape)

torch.Size([64, 1, 5])
torch.Size([64, 1, 5])


In [106]:
# tensor 에 additional dimension 을 더하고 싶다면....

x = torch.arange(10)   #  [10]
print(x)

print(x.unsqueeze(0))      # dimension-0 에 한 차원을 더 집어 넣는다. 
print(x.unsqueeze(1))      # dimension-1 에 한 차원을 더 집어 넣는다. 

# 앞으로 deep learning 프로젝트를 하는데, 사실 코드 자체는 얼마 안길고 쓰는 함수도 몇개 안된다..  다면 그 안을 타고 흐르는 이 tensor 들의 dimension 맞추기 게임이라는 것을 더 알게 된다 ㅠ.ㅠ   

print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([1, 10])
torch.Size([10, 1])


In [110]:
x = torch.arange(10).unsqueeze(0)
print(x)
x = x.unsqueeze(1)
print(x)    #  1x1x10 tensor 가 될것임
print(x.shape)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
torch.Size([1, 1, 10])


In [2]:
z = x.squeeze(dim=0)   #  차원을 하나 걷어내고 싶다면.... 걷어내고 싶은 dimension 에서 squeeze 를 불러주면 된다.    
print(z)
print(z.shape)

NameError: name 'x' is not defined

Deep Learning 이라는 것이 Tensor 가 신나게 Flow~~~ 하는 과정중에 dimension 맞추기 게임이라는 것을 알게 된다. 