In [1]:

import torch 
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

In [11]:
t = torch.tensor([ [1,2,3], [4,5,6]], dtype=torch.float64, requires_grad=True)
t.dtype, t.requires_grad

(torch.float64, True)

In [14]:
x = torch.empty(size=(3,3))
x = torch.zeros((3,3))
x = torch.rand((3,3))
x = torch.eye(5,5)   # 이것만 tuple 로 안받음
x = torch.arange(start=5, end=10, step=0.1, dtype=torch.float32)


In [18]:
np_array = np.zeros((5,5))
t = torch.from_numpy(np_array)
np_array_again = t.numpy()
np_array_again

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:

x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [23]:
x+y
print(x.dot(y).item())

32


In [33]:

x = torch.tensor([[10,2,3],[4,5,6]])

In [34]:
print(x.sum(dim=0))
print(x.sum(dim=1))

tensor([14,  7,  9])
tensor([15, 15])


In [36]:
print(x)
z = torch.argmax(x, dim=0)
print(z)
z = torch.argmax(x, dim=1)
print(z)

tensor([[10,  2,  3],
        [ 4,  5,  6]])
tensor([0, 1, 1])
tensor([0, 2])


In [37]:

batch_size = 5
features = 5
x = torch.rand( (batch_size, features))

In [38]:
print(x)

tensor([[0.3330, 0.2248, 0.5147, 0.4257, 0.3134],
        [0.3780, 0.4209, 0.4243, 0.1780, 0.8176],
        [0.7328, 0.3134, 0.4411, 0.5940, 0.9559],
        [0.5063, 0.1026, 0.5342, 0.2428, 0.2374],
        [0.4999, 0.5789, 0.9938, 0.6708, 0.2934]])


In [47]:
print(x.shape)
print(x[0].shape)
print(x[0])
print(x[:,0].unsqueeze(1))

torch.Size([5, 5])
torch.Size([5])
tensor([0.3330, 0.2248, 0.5147, 0.4257, 0.3134])
tensor([[0.3330],
        [0.3780],
        [0.7328],
        [0.5063],
        [0.4999]])


In [51]:
print(x[2, 0:3])
print(x[0,1].item())

tensor([0.7328, 0.3134, 0.4411])
0.2248018980026245


In [54]:
x = torch.arange(9)
x = x.view(3,3)
x = x.view(-1,3)

In [69]:
print(x.unsqueeze(dim=0))
print(x.unsqueeze(dim=1))
print(x.unsqueeze(dim=2))

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
tensor([[[0, 1, 2]],

        [[3, 4, 5]],

        [[6, 7, 8]]])
tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]],

        [[6],
         [7],
         [8]]])


In [77]:

x = torch.rand((2,5))
y = torch.rand((2,5))
print(x)
print(torch.cat((x, y), dim=0).shape)
print(torch.cat())

tensor([[0.6203, 0.3876, 0.0040, 0.5194, 0.1837],
        [0.7676, 0.1795, 0.6247, 0.2436, 0.8726]])
torch.Size([4, 5])
